### ISSUE TITLE
feature request: toggle whitespace diff on/off with splice command

### ISSUE THREAD

**Issue by dlamotte** [errael/splice9#16]
I could probably make a binding, but having it in the menu would be helpful.

**Comment by errael** [comment]
Opened a discussion, #17, about adding diff options in general.

**Comment by errael** [comment]
Greetings @dlamotte ,

I've added a property sheet dialog `Diff Options`, see https://github.com/errael/splice9/wiki/Dialogs#diff-options. It's in the v1.0.0-beta1 I just released. I'm thinking about having several unbound actions that one could could set up in the splice config, so some of the stuff can be a keyboard shortcut.

Comments on the behavior of the property sheet dialog welcome.

**Comment by errael** [comment]
https://github.com/errael/splice9/releases/tag/v1.0.0-RC1 is now available with a `Diff Options` dialog, see https://github.com/errael/splice9/wiki/Dialogs#diff-options.

Keyboard shortcuts post 1.0.0

**Comment by dlamotte** [comment]
Looks great. I've updated and will give it a try next time I end up using it (TBH, I don't use it much because most 3 way merges I see aren't so complicated).
